name: Create new version

on:
  push:
    branches:
      - "main"
      - "php8.2"
      - "php8.1"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      -
        name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      -
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
